export {
  PREVIEW_ONLY_BLOCK_MESSAGE,
  PREVIEW_ONLY_FINALIZE_BLOCK_MESSAGE,
  hasStubCarrierRoutes,
  isMelissaBuyerDoorEnabled,
  isMelissaBuyerDoorEnabledOnClient,
  isPreviewOnlyTargeting,
  isPreviewStripeTestCheckoutAllowed,
  isPreviewStripeTestCheckoutAllowedOnClient,
  melissaQuoteQuantity,
  normalizeMelissaMeta,
  parseEnvFlag,
  readMelissaTargeting,
  type MelissaListPreviewMeta,
  type MelissaRouteMeta,
  type MelissaTargetingMeta,
} from "@postcard-platform/api/lib/melissa-buyer-door";
