#!/usr/bin/env node
/**
 * Writes packages/db/.env from env vars (never commit .env).
 *
 * Option A — full URI (copy from Vercel DIRECT_URL):
 *   DATABASE_URL='postgresql://...' node scripts/sync-db-env.mjs
 *
 * Option B — password only:
 *   SUPABASE_DB_PASSWORD='your-db-password' node scripts/sync-db-env.mjs
 */
import { writeFileSync, copyFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dbDir = join(root, "packages/db");
const envPath = join(dbDir, ".env");
const examplePath = join(dbDir, ".env.example");

const HOST =
  "postgresql://postgres.onrvdowfqexfchjhysbm@aws-1-us-west-2.pooler.supabase.com:5432/postgres";

function buildFromPassword(password) {
  const user = "postgres.onrvdowfqexfchjhysbm";
  const encoded = encodeURIComponent(password);
  return `postgresql://${user}:${encoded}@aws-1-us-west-2.pooler.supabase.com:5432/postgres`;
}

let databaseUrl = process.env.DATABASE_URL?.trim();

if (!databaseUrl && process.env.SUPABASE_DB_PASSWORD?.trim()) {
  databaseUrl = buildFromPassword(process.env.SUPABASE_DB_PASSWORD.trim());
}

if (!databaseUrl) {
  if (!existsSync(envPath) && existsSync(examplePath)) {
    copyFileSync(examplePath, envPath);
    console.log("Created packages/db/.env from .env.example");
  }
  console.error(`
Missing credentials. Run ONE of:

  # Paste full URI from Vercel (DIRECT_URL) or Supabase dashboard:
  DATABASE_URL='postgresql://postgres.onrvdowfqexfchjhysbm:PASSWORD@aws-1-us-west-2.pooler.supabase.com:5432/postgres' npm run db:env:sync

  # Or password only:
  SUPABASE_DB_PASSWORD='your-password' npm run db:env:sync
`);
  process.exit(1);
}

if (databaseUrl.includes("REPLACE_ME") || databaseUrl.includes("[YOUR")) {
  console.error("DATABASE_URL still contains a placeholder. Use your real password or full URI.");
  process.exit(1);
}

const content = `# Local Prisma CLI only — same Supabase DB as Vercel
# Generated by: npm run db:env:sync

DATABASE_URL="${databaseUrl.replace(/"/g, '\\"')}"
`;

writeFileSync(envPath, content, "utf8");
console.log("Wrote packages/db/.env (DATABASE_URL set).");
